name: build check
on:
    pull_request:
        branches:
            - master
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: actions-rs/toolchain@v1
            with:
                toolchain: nightly
                default: true
                override: true
          - uses: ./.github/actions/alemian-saga-build-full
          - run: rustup component add clippy
            shell: bash
          - run: cargo clippy -- -D warnings
            shell: bash
            working-directory: alemian-saga-core
          - run: cargo clippy -- -D warnings
            shell: bash
            working-directory: alemian-saga

